apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: n8n
  labels:
    app: ui
data:
  WEBHOOK_URL: https://builder.frontiersin.io/
  N8N_EDITOR_BASE_URL: https://builder.frontiersin.io/
  DB_TYPE: postgresdb
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_HOST: hurricane-01-instance-1.ciflcdlz0b6m.eu-west-1.rds.amazonaws.com
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: n8n
  DB_POSTGRESDB_SCHEMA: public
  DB_POSTGRESDB_PASSWORD: 4J9dL5X3S7bE8hC0P9V2W4YLF2mG1T3K6DBQcN3P